// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPDcjqQc3IwWrqPu4lLhL59lu59nsVi8',
    appId: '1:895396446334:web:f001c6fd96273eaf7e182f',
    messagingSenderId: '895396446334',
    projectId: 'blabla-72f0c',
    authDomain: 'blabla-72f0c.firebaseapp.com',
    databaseURL: 'https://blabla-72f0c-default-rtdb.firebaseio.com',
    storageBucket: 'blabla-72f0c.firebasestorage.app',
    measurementId: 'G-8BJ6DJTQQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAls4WtMt7u-3DqboaHx7eWemLU-Sa8Jb4',
    appId: '1:895396446334:android:1c37af0ee40de6757e182f',
    messagingSenderId: '895396446334',
    projectId: 'blabla-72f0c',
    databaseURL: 'https://blabla-72f0c-default-rtdb.firebaseio.com',
    storageBucket: 'blabla-72f0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbG6ToZ563HQ9rffvsTEYWNAS1TaEnaws',
    appId: '1:895396446334:ios:12cb4ccb09d2fa607e182f',
    messagingSenderId: '895396446334',
    projectId: 'blabla-72f0c',
    databaseURL: 'https://blabla-72f0c-default-rtdb.firebaseio.com',
    storageBucket: 'blabla-72f0c.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbG6ToZ563HQ9rffvsTEYWNAS1TaEnaws',
    appId: '1:895396446334:ios:12cb4ccb09d2fa607e182f',
    messagingSenderId: '895396446334',
    projectId: 'blabla-72f0c',
    databaseURL: 'https://blabla-72f0c-default-rtdb.firebaseio.com',
    storageBucket: 'blabla-72f0c.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfPDcjqQc3IwWrqPu4lLhL59lu59nsVi8',
    appId: '1:895396446334:web:2f24ba3a1afa8ab27e182f',
    messagingSenderId: '895396446334',
    projectId: 'blabla-72f0c',
    authDomain: 'blabla-72f0c.firebaseapp.com',
    databaseURL: 'https://blabla-72f0c-default-rtdb.firebaseio.com',
    storageBucket: 'blabla-72f0c.firebasestorage.app',
    measurementId: 'G-CE7E9PYQBN',
  );
}
